### ISSUE TITLE
Alice crashes if only punctuation is input

### ISSUE THREAD

**Issue by jrha** [etattershall/toddler-chatbot#2]
i.e. emoticons

<details>
<summary>Stack Trace</summary>

```
>>> Why?

:-(
Traceback (most recent call last):
  File "alice.py", line 96, in <module>
    print('>>> ' + reply(fulltext) + '\n')
  File "alice.py", line 53, in reply
    first_word = re.findall('^\w+', first_word)[0]
IndexError: list index out of range
```
</details>

**Comment by GRyall** [comment]
This is a duplicate of #1 , though I clearly didn't give it a sensible name originally

**Comment by etattershall** [comment]
Fixed only-punctuation input error and added appropriate emoticon detection and response
